/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ringcentral.websocket.demo;

import com.ringcentral.RestException;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() throws RestException, IOException {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
